// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Nop.Web.Models
{
    public partial class InvoiceSell
    {
        [Key]
        [Column(TypeName = "decimal(28, 0)")]
        public decimal buildingNo { get; set; }
        [Key]
        public long invoiceNo { get; set; }
        [Required]
        [StringLength(20)]
        public string userNumber { get; set; }
        public short billTypeNo { get; set; }
        public short? billTypeSubNo { get; set; }
        [Column(TypeName = "decimal(28, 0)")]
        public decimal storeNo { get; set; }
        [Required]
        [StringLength(250)]
        public string aName { get; set; }
        [StringLength(250)]
        public string eName { get; set; }
        public bool? isCash { get; set; }
        [Column(TypeName = "date")]
        public DateTime dateG { get; set; }
        [StringLength(20)]
        public string dateH { get; set; }
        [Column(TypeName = "date")]
        public DateTime? deliveryDate { get; set; }
        [StringLength(20)]
        public string deliveryDateH { get; set; }
        public bool? isDelivered { get; set; }
        [Column(TypeName = "date")]
        public DateTime? deliveredDate { get; set; }
        [StringLength(20)]
        public string deliveredDateH { get; set; }
        public bool? isOutDelivery { get; set; }
        public long? invoiceJobStatusNo { get; set; }
        public long? invoiceStatusNo { get; set; }
        public long? shipType { get; set; }
        [Column(TypeName = "decimal(18, 6)")]
        public decimal? shipCost { get; set; }
        [StringLength(250)]
        public string shipTo { get; set; }
        public long? billToTypeNo { get; set; }
        [Column(TypeName = "decimal(28, 0)")]
        public decimal? billToBuildingNo { get; set; }
        [StringLength(27)]
        public string billTo { get; set; }
        public bool? isInventory1GaveIt { get; set; }
        public long? inventory1StaffNo { get; set; }
        public bool? isInventory2ReceivedIt { get; set; }
        public long? inventory2StaffNo { get; set; }
        public long? depositNo { get; set; }
        public long? itemStatus { get; set; }
        public bool? isPostedStock { get; set; }
        public bool? isDeleted { get; set; }
        public bool? isVoid { get; set; }
        public bool? isPosted { get; set; }
        public bool? isGLPosted { get; set; }
        public bool? isPayments { get; set; }
        public bool? isFastInvoice { get; set; }
        public bool? isDeposited { get; set; }
        public bool? isCleared { get; set; }
        [Column(TypeName = "decimal(18, 6)")]
        public decimal? amountLeftAfterAllBills { get; set; }
        [Column(TypeName = "decimal(18, 6)")]
        public decimal? collectedAmountFromOtherBills { get; set; }
        [StringLength(250)]
        public string note { get; set; }
        public bool? isItemOrUnit { get; set; }
        public long? personNo2 { get; set; }
        public int? carNo { get; set; }
        public long? driverNo { get; set; }
        [StringLength(250)]
        public string driverName { get; set; }
        public bool? isUseInOutInvoice { get; set; }
        [Column(TypeName = "decimal(27, 0)")]
        public decimal? regionNo { get; set; }
        public bool? isAccountingForOthers { get; set; }
        [Column(TypeName = "decimal(21, 0)")]
        public decimal? accountNo_Pay { get; set; }
        [Column(TypeName = "decimal(21, 0)")]
        public decimal? accountNo_Ship { get; set; }
        [Column(TypeName = "decimal(21, 0)")]
        public decimal? accountNo_Discount { get; set; }
        [StringLength(150)]
        public string name_Pay { get; set; }
        [StringLength(150)]
        public string name_Discount { get; set; }
        [StringLength(150)]
        public string name_Ship { get; set; }
        public long? billNo { get; set; }
        [Column(TypeName = "decimal(27, 0)")]
        public decimal? projectNo { get; set; }
        [Column(TypeName = "decimal(21, 0)")]
        public decimal? accountNo { get; set; }
        [Column(TypeName = "decimal(21, 0)")]
        public decimal? accountNo_Second { get; set; }
        public long? agentNo { get; set; }
        [Column(TypeName = "decimal(28, 0)")]
        public decimal? payBillNo { get; set; }
        public long? personNo { get; set; }
        public long? manPosted { get; set; }
        public long? manGLPosted { get; set; }
        public long? manVoid { get; set; }
        [StringLength(15)]
        public string telephone { get; set; }
        [Column(TypeName = "decimal(18, 6)")]
        public decimal? sumPayed { get; set; }
        [Column(TypeName = "decimal(18, 6)")]
        public decimal? subTotal { get; set; }
        [Column(TypeName = "decimal(18, 6)")]
        public decimal? subTotalDiscount { get; set; }
        [Column(TypeName = "decimal(18, 6)")]
        public decimal? subNetTotal { get; set; }
        [Column(TypeName = "decimal(18, 6)")]
        public decimal? subNetTotalPlusTax { get; set; }
        public int? subCount { get; set; }
        [Column(TypeName = "decimal(18, 6)")]
        public decimal? subLeftQuantity { get; set; }
        [Column(TypeName = "decimal(18, 6)")]
        public decimal? subQuantity { get; set; }
        [Column(TypeName = "decimal(18, 6)")]
        public decimal? amountCalculated { get; set; }
        [Column(TypeName = "decimal(18, 6)")]
        public decimal? discount { get; set; }
        [Column(TypeName = "decimal(18, 6)")]
        public decimal? totalDiscount { get; set; }
        [Column(TypeName = "decimal(18, 6)")]
        public decimal? amountPayed01 { get; set; }
        [Column(TypeName = "decimal(18, 6)")]
        public decimal? amountPayed02 { get; set; }
        [Column(TypeName = "decimal(18, 6)")]
        public decimal? amountPayed03 { get; set; }
        [Column(TypeName = "decimal(18, 6)")]
        public decimal? amountPayed04 { get; set; }
        [Column(TypeName = "decimal(18, 6)")]
        public decimal? amountPayed05 { get; set; }
        [Column(TypeName = "decimal(18, 6)")]
        public decimal? amountLeft { get; set; }
        [Column(TypeName = "decimal(18, 6)")]
        public decimal? amountCalculatedPayed { get; set; }
        [Column(TypeName = "date")]
        public DateTime? requestShipDate { get; set; }
        public short? paymentTermsId { get; set; }
        [Column(TypeName = "date")]
        public DateTime? dueDate { get; set; }
        public short? pricingSchemeId { get; set; }
        [Column(TypeName = "date")]
        public DateTime? pickedDate { get; set; }
        [Column(TypeName = "date")]
        public DateTime? packedDate { get; set; }
        public bool? isCompleted { get; set; }
        public short? taxingSchemeNo { get; set; }
        [Column(TypeName = "decimal(12, 7)")]
        public decimal? taxRate1_Percentage { get; set; }
        [Column(TypeName = "decimal(12, 7)")]
        public decimal? taxRate2_Percentage { get; set; }
        public bool? isCalculateTax2OnTax1 { get; set; }
        [StringLength(150)]
        public string taxRate1eName { get; set; }
        [StringLength(150)]
        public string taxRate2eName { get; set; }
        public bool? isTax1OnShipping { get; set; }
        public bool? isTax2OnShipping { get; set; }
        [StringLength(150)]
        public string taxRate1aName { get; set; }
        [StringLength(150)]
        public string taxRate2aName { get; set; }
        public short? taxRateNo2 { get; set; }
        [Column(TypeName = "decimal(18, 6)")]
        public decimal? taxRate1_Total { get; set; }
        [Column(TypeName = "decimal(18, 6)")]
        public decimal? taxRate2_Total { get; set; }
        public bool? isOneInvoiceUploaded { get; set; }
        public short? taxRateNo { get; set; }
        [Column(TypeName = "decimal(28, 0)")]
        public decimal? cashRegisterNo_BuildingNo { get; set; }
        [StringLength(50)]
        public string invoiceVATID { get; set; }
        [Column(TypeName = "decimal(21, 0)")]
        public decimal? clientVendorNo { get; set; }
        public bool? isUploadedToMainBranch { get; set; }
        public bool? isPostedToTransactions { get; set; }
        [Column(TypeName = "date")]
        public DateTime? dateG_PerDay { get; set; }
        public int? dateG_PerMonth { get; set; }
        public int? dateG_PerYearQuarter { get; set; }
        public int? dateG_PerYearHalf { get; set; }
        public int? dateG_PerYear { get; set; }
        public short? VATTypeNo { get; set; }
        public short? VATGroupNo { get; set; }
        [Column(TypeName = "decimal(18, 6)")]
        public decimal? profitMarginTotal { get; set; }
        [Column(TypeName = "date")]
        public DateTime? dateG_Posted { get; set; }
        [Column(TypeName = "date")]
        public DateTime? dateG_GLPosted { get; set; }
        [StringLength(50)]
        public string mainContact1 { get; set; }
        [StringLength(50)]
        public string mainContact2 { get; set; }
        [StringLength(50)]
        public string mainContact3 { get; set; }
        [StringLength(21)]
        public string amountPayed01_VoucherNo { get; set; }
        [StringLength(21)]
        public string amountPayed02_VoucherNo { get; set; }
        [StringLength(21)]
        public string amountPayed03_VoucherNo { get; set; }
        [StringLength(21)]
        public string amountPayed04_VoucherNo { get; set; }
        [StringLength(21)]
        public string amountPayed05_VoucherNo { get; set; }
        [Column(TypeName = "decimal(21, 0)")]
        public decimal? amountPayed01_bankAccountNo { get; set; }
        [Column(TypeName = "decimal(21, 0)")]
        public decimal? amountPayed02_bankAccountNo { get; set; }
        [Column(TypeName = "decimal(21, 0)")]
        public decimal? amountPayed03_bankAccountNo { get; set; }
        [Column(TypeName = "decimal(21, 0)")]
        public decimal? amountPayed04_bankAccountNo { get; set; }
        [Column(TypeName = "decimal(21, 0)")]
        public decimal? amountPayed05_bankAccountNo { get; set; }
        [Column(TypeName = "decimal(18, 6)")]
        public decimal? customerCashGiven { get; set; }
        [Column(TypeName = "decimal(18, 6)")]
        public decimal? customerCashReturned { get; set; }
        [Column(TypeName = "decimal(18, 6)")]
        public decimal? price_differenceFromFirstPriceTotal { get; set; }
        public int? print_numOfCopies { get; set; }
        [Column(TypeName = "date")]
        public DateTime? print_DateG { get; set; }
        [Column(TypeName = "date")]
        public DateTime? leftMoneyPaymentDate { get; set; }
        public long? normalCustomerTypeNo { get; set; }
        public bool? isPrintPartial { get; set; }
        [Column(TypeName = "decimal(13, 6)")]
        public decimal? cardAmount_Visa { get; set; }
        [Column(TypeName = "decimal(13, 6)")]
        public decimal? cardAmount_SPAN { get; set; }
        public int? dailyBillNo { get; set; }
        [Column(TypeName = "decimal(22, 6)")]
        public decimal? runningCostAvg_diffrenceWhithPriceTotal { get; set; }
        [Column(TypeName = "decimal(22, 6)")]
        public decimal? profitMarginTotal_fromAvgCost { get; set; }
        [Column(TypeName = "decimal(22, 6)")]
        public decimal? runningCostAvgTotal { get; set; }
        [Column(TypeName = "decimal(18, 6)")]
        public decimal? buyPrice_costPriceTotal { get; set; }
        [Column(TypeName = "decimal(18, 6)")]
        public decimal? primaryUnit_QuantityTotal { get; set; }
        [StringLength(20)]
        public string paperBillNum { get; set; }
        [StringLength(20)]
        public string gazElectric_InNum { get; set; }
        [StringLength(20)]
        public string gaztElectric_OutNum { get; set; }
        public bool? isReturnedFullyByReturnInvoice { get; set; }
        [Column(TypeName = "date")]
        public DateTime? isReturnedFullyByReturnInvoiceDate { get; set; }
        [Column(TypeName = "decimal(18, 6)")]
        public decimal? weightTotal { get; set; }
        public long? staffNo1_personNo { get; set; }
        public long? staffNo2_personNo { get; set; }
        public long? staffNo3_personNo { get; set; }
        public long? exportImportType { get; set; }
        public long? billCreatorAsOf { get; set; }
        [StringLength(27)]
        public string IDCard { get; set; }
        public long? billPaperType { get; set; }
        [StringLength(50)]
        public string paymentTypes { get; set; }
        [Column(TypeName = "decimal(18, 6)")]
        public decimal? subNetTotal_ExecludingTax { get; set; }
        [Column(TypeName = "decimal(13, 6)")]
        public decimal? device_mileage { get; set; }
        public int? device_makerNo { get; set; }
        [StringLength(150)]
        public string device_model { get; set; }
        [StringLength(27)]
        public string device_plate { get; set; }
        [StringLength(27)]
        public string device_serial_1 { get; set; }
        [StringLength(27)]
        public string device_serial_2 { get; set; }
        [Column(TypeName = "decimal(13, 6)")]
        public decimal? device_next_mileage { get; set; }
        [Column(TypeName = "date")]
        public DateTime? device_next_serviceDate { get; set; }
        [StringLength(20)]
        public string device_next_serviceDateH { get; set; }
        public int? device_makeYear { get; set; }
        public short? Inv_billTypeNo { get; set; }
        [Column(TypeName = "decimal(28, 0)")]
        public decimal? Inv_buildingNo { get; set; }
        public long? Inv_invoiceNo { get; set; }
        [StringLength(20)]
        public string Inv_userNumber { get; set; }
        [Column(TypeName = "decimal(18, 6)")]
        public decimal? calculatedPayed { get; set; }
        [Column(TypeName = "decimal(18, 6)")]
        public decimal? amountPayed { get; set; }
        [Column(TypeName = "decimal(18, 6)")]
        public decimal? calculatedCreditAmount { get; set; }
        [Column(TypeName = "decimal(18, 6)")]
        public decimal? calculatedDebitAmount { get; set; }
        public bool? isCreateGlass { get; set; }
        public long? rentType { get; set; }
        [Column(TypeName = "date")]
        public DateTime? rentDate { get; set; }
        [Column(TypeName = "date")]
        public DateTime? rentReturnDate { get; set; }
        [Column(TypeName = "decimal(18, 6)")]
        public decimal? rentQuantity { get; set; }
        public int? service { get; set; }
        public bool? isHangerOrFold { get; set; }
        public bool? isSpot { get; set; }
        public bool? isFastCleaning { get; set; }
        public long? starchNo { get; set; }
        public long? blueWeightNo { get; set; }
        public bool? isLost { get; set; }
        public bool? isPaperInvoiceReturned { get; set; }
        public long? spoilTypeNo { get; set; }
        [Column(TypeName = "decimal(14, 6)")]
        public decimal? trainingHourseToBeGiven { get; set; }
        [Column(TypeName = "decimal(14, 6)")]
        public decimal? trainingHourseLeft { get; set; }
        [StringLength(20)]
        public string gaztInvoiceNumber { get; set; }
        [StringLength(40)]
        public string gaztUniqueInvoiceIdentifier { get; set; }
        public short? gaztInvoiceTypeCode { get; set; }
        public short? gaztInvoiceTypeCode_SubType { get; set; }
        [Column(TypeName = "date")]
        public DateTime? gaztLatestDeliveryDate { get; set; }
        [StringLength(100)]
        public string gaztInvoiceHash { get; set; }
        [StringLength(100)]
        public string gaztPreviousInvoiceHash { get; set; }
        public byte[] row_timestamp { get; set; }
    }
}